nodeLinker: pnp
enableGlobalCache: false
enableTelemetry: false
supportedArchitectures:
  os:
    - linux
    - win32
    - darwin
  cpu:
    - x64
packageExtensions:
  'ts-evaluator@1.2.0':
    dependencies:
      typescript: '5.2.2'
